name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install npm dependencies
        run: npm ci

      - name: Hugo build
        run: |
          export HUGO_COMMIT_HASH=$(git rev-parse --short HEAD)
          export HUGO_CACHE_BUST=$(date +%s)
          hugo --minify --gc --baseURL "https://golfed.xyz/"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=golfed-xyz
