name: Deploy to Pages

on:
  push:
    brances: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# allow only one concurrent deployment, however don't cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true # necessary for sass support

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Create CNAME file for custom domain
        run: |
          echo "golfed.xyz" > ./static/CNAME

      - name: Hugo build
        run: |
          export HUGO_COMMIT_HASH=$(git rev-parse --short HEAD)
          export HUGO_CACHE_BUST=$(date +%s)
          hugo --minify --gc --baseURL "https://golfed.xyz/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
