name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.147.9

      - name: Hugo build
        run: |
          export HUGO_COMMIT_HASH=$(git rev-parse --short HEAD)
          hugo --minify --gc

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.PORT }}" \
            public/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.REMOTE_PATH }}
